name: CD Pipeline

on:
  push:
    branches:
      - feat/test_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Deploy on EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > emotipet-backend.pem && chmod 600 emotipet-backend.pem
          echo "Private key content:"
          cat emotipet-backend.pem

          ssh -v -o StrictHostKeyChecking=no -i emotipet-backend.pem ${USER}@${EC2_HOST} << 'EOF'
            set -e

            APP_DIR="/home/ubuntu/emotipet-microservice-backend"
            echo "APP_DIR: $APP_DIR"

            if [ -d "$APP_DIR" ]; then
              cd $APP_DIR
              git pull origin main
            else
              git clone https://github.com/ddl-devs/emotipet-microservice-backend.git $APP_DIR
              cd $APP_DIR
            fi

            cp /home/ubuntu/.env $APP_DIR/.env

            docker build -t fastapi-app:latest .

            docker stop fastapi-container || true
            docker rm fastapi-container || true

            docker run -d --name fastapi-container -p 8000:8000 --env-file $APP_DIR/.env fastapi-app:latest
          EOF