name: CD Pipeline

on:
  push:
    branches:
      - feat/test_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Deploy on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$PRIVATE_KEY" > emotipet.pem && chmod 600 emotipet.pem

          ssh -o StrictHostKeyChecking=no -i emotipet.pem ${USER}@${HOST} << 'EOF'
            set -e  # Exit on error

            APP_DIR="/home/ubuntu/emotipet-microservice-backend"

            if [ -d "$APP_DIR" ]; then
              cd $APP_DIR
              git pull origin main
            else
              git clone https://github.com/ddl-devs/emotipet-microservice-backend.git $APP_DIR
              cd $APP_DIR
            fi

            cp /home/ubuntu/.env $APP_DIR/.env

            docker build -t fastapi-app:latest .

            docker stop fastapi-container || true
            docker rm fastapi-container || true

            docker run -d --name fastapi-container -p 8000:8000 --env-file $APP_DIR/.env fastapi-app:latest
          EOF